# THIS FILE IS AUTO-GENERATED BY setup.py

version = "3.4.1-"

# Some build-time constants:
HTTPD = "/usr/sbin/httpd"
HTTPD_VERSION = "2.2.15"
APR_VERSION = "1.3.9"
LIBEXECDIR = "/usr/lib64/httpd/modules"
SYSCONFDIR = ""
TEST_MOD_PYTHON_SO = "/home/cheungssh/soft/mod_python-3.4.1/src/mod_python.so" #NB: This is for test.py only
TESTHOME = "/home/cheungssh/soft/mod_python-3.4.1/test"
PYTHON_BIN = "/usr/bin/python"
