/* Generated by the Systemtap dtrace wrapper */

#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* PYTHON_FUNCTION_ENTRY ( const char *, const char *, int) */
#if defined STAP_SDT_V1
#define PYTHON_FUNCTION_ENTRY_ENABLED() __builtin_expect (function__entry_semaphore, 0)
#define python_function__entry_semaphore function__entry_semaphore
#else
#define PYTHON_FUNCTION_ENTRY_ENABLED() __builtin_expect (python_function__entry_semaphore, 0)
#endif
__extension__ extern unsigned short python_function__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PYTHON_FUNCTION_ENTRY(arg1,arg2,arg3) \
DTRACE_PROBE3(python,function__entry,arg1,arg2,arg3)

/* PYTHON_FUNCTION_RETURN ( const char *, const char *, int) */
#if defined STAP_SDT_V1
#define PYTHON_FUNCTION_RETURN_ENABLED() __builtin_expect (function__return_semaphore, 0)
#define python_function__return_semaphore function__return_semaphore
#else
#define PYTHON_FUNCTION_RETURN_ENABLED() __builtin_expect (python_function__return_semaphore, 0)
#endif
__extension__ extern unsigned short python_function__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PYTHON_FUNCTION_RETURN(arg1,arg2,arg3) \
DTRACE_PROBE3(python,function__return,arg1,arg2,arg3)

